### ISSUE TITLE
Ricochet Subgraph

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-analytics#10]
This issue is to make a Ricoceht Subgraph

**Comment by JoshuaTrujillo15** [comment]
Recommended Spec for this bounty:

Event Entities:

- Distribution Event
    - total distributed
    - total collected
    - fee collected
    - in token (optional)
    - out token (optional)

- UpdatedStream Event
    - from
    - new flow rate
    - new net flow rate
    - Distribution Event

Non-Event Entities:

- Stream
    - Streamer
    - UpdatedStream Events
    - flow rate
    - last update
    - total streamed since last update
    - total received

- Market
    - Distribution Events
    - Streams
    - in token
    - out token

- Streamer
    - address
    - Streams
    - Markets

- Keeper
    - Distribution Events
    - address
    - total distributions

**Comment by josealonso** [comment]
@pitko is doing it, not me. I'm just like a placeholder.
