### ISSUE TITLE
Fix Dune Analytics Dashboard

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-analytics#11]
Some of the queries in the Ricochet Exchange dashboard I made on Dune are broken: https://dune.xyz/mikeghen1/Ricochet-Exchange

This issue is to fix these queries

**Comment by lucasz-hu** [comment]
Just reran the queries and everything seems fine now. I will investigate, possibly an outage? Was this one-time issue or recurring?

**Comment by josealonso** [comment]
Closing this issue.
