### ISSUE TITLE
Ricochet Analytics API Server

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-analytics#14]
Host the Ricochet analytics flask app `03-endpoint` and work with me to get DNS setup

**Comment by theSchein** [comment]
im on this

**Comment by MrSquiggles13** [comment]
Ive found something better. I think we can build something awesome i wanna show you @mikeghen plus @theSchein if you want in. I really think we can make something really really cool

**Comment by theSchein** [comment]
this is just a simple endpoint for CG and other trackers to get our relevant token metrics. I have a PR here for review:

https://github.com/Ricochet-Exchange/ricochet-analytics/pull/17
