### ISSUE TITLE
Coingecko vs. Launchpad Price

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-analytics#21]
I keep noticing that the launchpad price is often higher than Coingecko. Its a pretty good metric so I'm opening this issue for someone to make a chart that overlays the two time series on top of each other. 
![IMG_4788](https://user-images.githubusercontent.com/5077880/153921303-44436690-ae66-468a-b1de-81a305c816bf.jpg)

**Comment by spitko** [comment]
I'll try to do this in Dune.

**Comment by spitko** [comment]
Query available here: https://dune.xyz/queries/424235

1. Added RIC token to [prices.usd table](https://github.com/duneanalytics/abstractions/pull/836).
2. Submitted RicochetLaunchpad contract to Dune; it is now decoded and can be queried using `ricochet_exchange."RicochetLaunchpad_v1*"` tables.
