### ISSUE TITLE
Update Dune Analytics for REX Markets v2.0

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-analytics#26]
This task is to update the queries in Dune Analytics to point to the newest REX Markets, Find these in the docs: https://docs.ricochet.exchange/docs/network-directory#rex-markets

<img width="1415" alt="Screen Shot 2022-03-10 at 5 34 28 PM" src="https://user-images.githubusercontent.com/5077880/157766335-50fdcf49-e9a7-4c09-8cb5-575f3ff24419.png">

**Comment by spitko** [comment]
I can do this tomorrow

**Comment by spitko** [comment]
Created a new query for monthly TVS: https://dune.xyz/queries/496878

USD rate is calculated from daily average price per token

**Comment by spitko** [comment]
@mikeghen Updated market addresses in query to new ones from staging
