### ISSUE TITLE
Commit SQL Queries from Dune Dashboard

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-analytics#5]
This issue involves going into Dune Analytics to get the queries from this dashboard https://dune.xyz/mikeghen1/Ricochet-Exchange, into this repo

**Comment by nishit-g** [comment]
Hey @mikeghen , can I work on this ? I went through the documentation of Dune Analytics and think I can do this. 
You need all the queries in different files or in a single file ?

**Comment by mikeghen** [comment]
@nishit-g see #11, there's some fixes that need to happen but this can be part of that issue, can you look at doing this and #11

**Comment by josealonso** [comment]
@lucasz-hu, if the existing query is working, this issue can be closed, is it correct ?

**Comment by josealonso** [comment]
This is part of #11, so closing it too.
