### ISSUE TITLE
Bank Borrow/Lend Dashboard

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-analytics#7]
Create a dashboard that shows how much has been borrowed and repaid by the REX Bank. There's a VaultBorrow, VaultRepay events that should be used. I perfer to do this in Dune, but using web3py/js would be acceptable too. in the case of using web3, make a script that can be run on the command line and will output results to the console.

**Comment by spitko** [comment]
Created a dune query here: https://dune.xyz/queries/384717
Let me know if any changes are required

**Comment by spitko** [comment]
Above query is now live on the main Dune dashboard
https://dune.xyz/mikeghen1/Ricochet-Exchange -> https://dune.xyz/queries/386203/736196

**Comment by josealonso** [comment]
@spitko, submit that query as a PR equivalent
