### ISSUE TITLE
DAO Treasury Net Worth

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-analytics#8]
This issue involves using web3py or similar to get the actual treasury balance. The treasury balance is the sum of:
1. The erc20/supertokens
2. The USDC on loan at the bank

1. For getting the erc20 and supertoken balances, use polygonscan and query balances for the tokens listed in the RIC network directory: https://docs.ricochet.exchange/docs/network-directory#super-tokens (Skip LP tokens they're de minimus)

2. The amount on loan at the bank requires you to query the blockchain for `VaultBorrow` and `VaultRepay` the amount in the bank is:
```
sum(vaultBorrows) - sum(vaultRepayments) + balanceOf USDC in the contract
```
There's three bank contracts listed in the network directory: https://docs.ricochet.exchange/docs/network-directory#rex-banks

You can use Polygonscan and export the ERC20 transactions for the bank contract and do this math in google sheets to verify it. See this document for querying for event history on chain: https://web3py.readthedocs.io/en/stable/filters.html#event-log-filters

**Comment by MrSquiggles13** [comment]
Gonna crank this one out instead I know I can get this one done no problem

**Comment by josealonso** [comment]
I'm not doing this task. @dov or @MrSquiggles13 are doing it.

**Comment by dov** [comment]
@josealonso You got the wrong dov.

**Comment by MrSquiggles13** [comment]
Yeah I'm like half way done

**Comment by MrSquiggles13** [comment]
For some reason i am unable to query the banks events. Working on a way to atleast call events needed then work on an ultimate fix for this bug

**Comment by MrSquiggles13** [comment]
Been able to query events just have to figure out the best way to space out the batches so i dont get rate limited then we will be golden

**Comment by MrSquiggles13** [comment]
I did it

**Comment by josealonso** [comment]
> I did it

You might want put a link to your PR or something similar.

**Comment by MrSquiggles13** [comment]
https://github.com/Ricochet-Exchange/ricochet-analytics/pull/16

Finished put comments with commits any questions please let me know
